In [2]:
import numpy as np

In [3]:
# 1. Create a null vector of size 10 but the fifth value which is 1.
null_vector = np.zeros(10)
null_vector[4] = 1
print("Null vector with 5th value as 1:", null_vector)

Null vector with 5th value as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
# 2. Create a vector with values ranging from 10 to 49.
vector_10_to_49 = np.arange(10, 50)
print("Vector from 10 to 49:", vector_10_to_49)

Vector from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:\n", matrix_3x3)

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr)
print("Indices of non-zero elements:", nonzero_indices)

Indices of non-zero elements: (array([0, 1, 4]),)


In [7]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_array_10x10 = np.random.rand(10, 10)
min_value = np.min(random_array_10x10)
max_value = np.max(random_array_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.0044571754227868965
Maximum value: 0.9967876073036632


In [8]:
# 6. Create a random vector of size 30 and find the mean value.
random_vector_30 = np.random.rand(30)
mean_value = np.mean(random_vector_30)
print("Mean value of the random vector:", mean_value)

Mean value of the random vector: 0.4355295782268428
